version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fortichain_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fortichain_user
      POSTGRES_PASSWORD: fortichain_password
      POSTGRES_DB: fortichain_db
    volumes:
      - fortichain_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fortichain_user -d fortichain_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  fortichain_data:
    driver: local
